# Generated by Django 5.2.5 on 2025-08-14 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='core.direction')),
            ],
            options={
                'unique_together': {('nom', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departement')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction')),
            ],
        ),
        migrations.CreateModel(
            name='EmailHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.EmailField(max_length=254)),
                ('manager_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('objet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='emails_pdfs/')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.collaborateur')),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_nom', models.CharField(max_length=255)),
                ('date_import', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_lignes', models.PositiveIntegerField(default=0)),
                ('total_anomalies', models.PositiveIntegerField(default=0)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entree', models.TimeField(blank=True, null=True)),
                ('sortie', models.TimeField(blank=True, null=True)),
                ('temps_presence_reel', models.CharField(blank=True, max_length=20, null=True)),
                ('temps_presence_theorique', models.CharField(blank=True, max_length=20, null=True)),
                ('entree_tardive', models.BooleanField(default=False)),
                ('sortie_anticipee', models.BooleanField(default=False)),
                ('absence_justifiee', models.CharField(blank=True, max_length=50, null=True)),
                ('absence_non_justifiee', models.BooleanField(default=False)),
                ('anomalie_badgeage_impair', models.BooleanField(default=False)),
                ('jour_tt_planifie', models.BooleanField(default=False)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='core.collaborateur')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('collaborateur', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_anomalie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_detection', models.DateTimeField(default=django.utils.timezone.now)),
                ('pointage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.pointage')),
            ],
        ),
    ]
