# Generated by Django 5.2.5 on 2025-08-14 12:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_manager', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='emails_pdfs/')),
                ('status', models.CharField(default='SENT', max_length=20)),
            ],
            options={
                'verbose_name': 'Email historique',
                'verbose_name_plural': 'Emails historiques',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HolidayMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Jour férié (MA)',
                'verbose_name_plural': 'Jours fériés (MA)',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': "Lot d'import",
                'verbose_name_plural': "Lots d'import",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeleworkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='emailhistorique',
            name='collaborateur',
        ),
        migrations.RemoveField(
            model_name='importhistorique',
            name='utilisateur',
        ),
        migrations.AlterModelOptions(
            name='anomalie',
            options={'ordering': ['-pointage__date', '-date_detection']},
        ),
        migrations.AlterModelOptions(
            name='collaborateur',
            options={'ordering': ['matricule']},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['direction__nom', 'nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['nom'], 'verbose_name': 'Direction', 'verbose_name_plural': 'Directions'},
        ),
        migrations.AlterModelOptions(
            name='pointage',
            options={'ordering': ['-date', 'collaborateur__matricule']},
        ),
        migrations.RenameField(
            model_name='pointage',
            old_name='anomalie_badgeage_impair',
            new_name='badgeage_impair',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='type_anomalie',
        ),
        migrations.RemoveField(
            model_name='collaborateur',
            name='manager_email',
        ),
        migrations.AddField(
            model_name='anomalie',
            name='detail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='is_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='is_telework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='type',
            field=models.CharField(choices=[('ENTREE_TARDIVE', 'Entrée tardive'), ('SORTIE_ANTICIPEE', 'Sortie anticipée'), ('ABSENCE_NON_JUSTIFIEE', 'Absence non justifiée'), ('BADGEAGE_IMPAIR', 'Badgeage impair')], default='ENTREE_TARDIVE', max_length=32),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointage',
            name='absence_justifiee_heures',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pointage',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.departement'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='date_detection',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='matricule',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='prenom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='direction',
            name='nom',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='absence_non_justifiee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collaborateur'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='entree_tardive',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='sortie_anticipee',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='temps_presence_reel',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='temps_presence_theorique',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['type'], name='core_anomal_type_46d568_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['date_detection'], name='core_anomal_date_de_62d5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborateur',
            index=models.Index(fields=['matricule'], name='core_collab_matricu_2cbe93_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborateur',
            index=models.Index(fields=['departement'], name='core_collab_departe_32b713_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborateur',
            index=models.Index(fields=['direction'], name='core_collab_directi_d57cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborateur',
            index=models.Index(fields=['manager'], name='core_collab_manager_d65e90_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['nom'], name='core_depart_nom_762f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='departement',
            index=models.Index(fields=['direction'], name='core_depart_directi_cee0fb_idx'),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.collaborateur'),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.importbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pointage',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='core.importbatch'),
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together={('collaborateur', 'date', 'batch')},
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date'], name='core_pointa_date_75a80c_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['departement'], name='core_pointa_departe_970cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['direction'], name='core_pointa_directi_01ccac_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['batch'], name='core_pointa_batch_i_8128d6_idx'),
        ),
        migrations.AddField(
            model_name='leave',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collaborateur'),
        ),
        migrations.AddField(
            model_name='teleworkday',
            name='collaborateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collaborateur'),
        ),
        migrations.DeleteModel(
            name='EmailHistorique',
        ),
        migrations.DeleteModel(
            name='ImportHistorique',
        ),
        migrations.AddIndex(
            model_name='emailhistory',
            index=models.Index(fields=['to_email'], name='core_emailh_to_emai_e499ff_idx'),
        ),
        migrations.AddIndex(
            model_name='emailhistory',
            index=models.Index(fields=['status'], name='core_emailh_status_afad81_idx'),
        ),
        migrations.AddIndex(
            model_name='emailhistory',
            index=models.Index(fields=['batch'], name='core_emailh_batch_i_f7cf2a_idx'),
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='absence_justifiee',
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['collaborateur', 'date'], name='core_leave_collabo_4eee66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together={('collaborateur', 'date')},
        ),
        migrations.AddIndex(
            model_name='teleworkday',
            index=models.Index(fields=['collaborateur', 'date'], name='core_telewo_collabo_85a866_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teleworkday',
            unique_together={('collaborateur', 'date')},
        ),
    ]
