# Generated by Django 5.2.5 on 2025-08-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailhistory_holidayma_importbatch_leave_teleworkday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalie',
            name='type',
            field=models.CharField(choices=[('ENTREE_TARDIVE', 'Entrée tardive'), ('SORTIE_ANTICIPEE', 'Sortie anticipée'), ('ABSENCE_NON_JUSTIFIEE', 'Absence non justifiée'), ('BADGEAGE_IMPAIR', 'Badgeage impair'), ('PRESENCE_INSUFFISANTE', 'Présence insuffisante')], default='ENTREE_TARDIVE', max_length=32),
        ),
    ]
