# Generated by Django 5.2.5 on 2025-08-18 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_anomalie_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='emailhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='holidayma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='importbatch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teleworkday',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='anomalie',
            name='core_anomal_type_46d568_idx',
        ),
        migrations.RemoveIndex(
            model_name='anomalie',
            name='core_anomal_date_de_62d5f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='collaborateur',
            name='core_collab_matricu_2cbe93_idx',
        ),
        migrations.RemoveIndex(
            model_name='collaborateur',
            name='core_collab_departe_32b713_idx',
        ),
        migrations.RemoveIndex(
            model_name='collaborateur',
            name='core_collab_directi_d57cd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='collaborateur',
            name='core_collab_manager_d65e90_idx',
        ),
        migrations.RemoveIndex(
            model_name='departement',
            name='core_depart_nom_762f9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='departement',
            name='core_depart_directi_cee0fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailhistory',
            name='core_emailh_to_emai_e499ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailhistory',
            name='core_emailh_status_afad81_idx',
        ),
        migrations.RemoveIndex(
            model_name='emailhistory',
            name='core_emailh_batch_i_f7cf2a_idx',
        ),
        migrations.RemoveIndex(
            model_name='leave',
            name='core_leave_collabo_4eee66_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointage',
            name='core_pointa_date_75a80c_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointage',
            name='core_pointa_departe_970cf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointage',
            name='core_pointa_directi_01ccac_idx',
        ),
        migrations.RemoveIndex(
            model_name='pointage',
            name='core_pointa_batch_i_8128d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='teleworkday',
            name='core_telewo_collabo_85a866_idx',
        ),
        migrations.AlterUniqueTogether(
            name='leave',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teleworkday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='departement',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='type',
            field=models.CharField(choices=[('ENTREE_TARDIVE', 'Entrée tardive'), ('SORTIE_ANTICIPEE', 'Sortie anticipée'), ('ABSENCE_NON_JUSTIFIEE', 'Absence non justifiée'), ('BADGEAGE_IMPAIR', 'Badgeage impair'), ('PRESENCE_INSUFFISANTE', 'Présence insuffisante')], max_length=32),
        ),
        migrations.AlterField(
            model_name='departement',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.direction'),
        ),
        migrations.AlterUniqueTogether(
            name='pointage',
            unique_together={('collaborateur', 'date')},
        ),
    ]
