# Generated by Django 5.2.5 on 2025-08-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_anomalie_options_alter_departement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='pointage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_history', to='core.pointage'),
        ),
    ]
